# Default values for temp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

temp:

  replicaCount: 1
  
  image:
    repository: temp
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v0.1.1"
  
  ingress:
    enabled: true
    className: "nginx"
    annotations:
    - kubernetes.io/ingress.class: nginx
    hosts:
      - host: kubernetes.docker.internal
        paths:
          - path: /temp
            pathType: prefix

