controller:
  component: rollouts-controller
  image:
    registry: quay.io
    repository: argoproj/argo-rollouts
    tag: ""
    pullPolicy: IfNotPresent

  ## Readiness and liveness probes for rollouts controller
  livenessProbe:
    httpGet:
      path: /
  readinessProbe:
    httpGet:
      path: /

dashboard:
  enabled: true