controller:
  component: rollouts-controller
  image:
    registry: quay.io
    repository: argoproj/argo-rollouts
    tag: ""
    pullPolicy: IfNotPresent

  ## Readiness and liveness probes for rollouts controller
  livenessProbe:
    httpGet:
      path: /metrics
      port: 8090
    initialDelaySeconds: 60
    periodSeconds: 20
    failureThreshold: 3
    successThreshold: 1
    timeoutSeconds: 10
  readinessProbe:
    httpGet:
      path: /metrics
      port: 8090
    initialDelaySeconds: 30
    periodSeconds: 5
    failureThreshold: 3
    successThreshold: 1
    timeoutSeconds: 4

dashboard:
  enabled: true