apiVersion: v2
appVersion: v2.1.7
description: A Helm chart for ArgoCD, a declarative, GitOps continuous delivery tool for Kubernetes.
name: argo-cd
version: 0.1.0
keywords:
  - argoproj
  - argocd
  - gitops
maintainers:
  - name: jordan
  - name: lucas
  - name: sam
dependencies:
  - name: argo-cd
    version: 3.28.1
    repository: https://argoproj.github.io/argo-helm/charts