apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: flask
Name: flask
repo: https://lucasrod16.github.io/helm-charts/
chartVersion: 0.1.2

releaseName: flask-app
releaseNamespace: flask
values: values.yaml
