apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: ingress-nginx
Name: ingress-nginx
repo: https://lucasrod16.github.io/helm-charts/
chartVersion: 0.1.0
configHome: /home/argocd/.config/helm
releaseName: ingress-nginx
releaseNamespace: ingress-nginx
values: values.yaml
