## ArgoCD configuration
## Ref: https://github.com/argoproj/argo-cd
##

global:
  image:
    repository: registry.hub.docker.com/lucasrod96/argocd
    tag: "v2.2.0-lr"
    
server: 
  service:
    type: NodePort
    
  config: 
    kustomize.buildOptions: '--enable-helm'
