## ArgoCD configuration
## Ref: https://github.com/argoproj/argo-cd
##

global:
  image:
    # -- If defined, a repository applied to all ArgoCD deployments
    repository: registry.hub.docker.com/lucasrod96/argocd
    # -- Overrides the global ArgoCD image tag whose default is the chart appVersion
    tag: "v2.2.0-lr"
    # -- If defined, a imagePullPolicy applied to all ArgoCD deployments
    imagePullPolicy: IfNotPresent

server: 
  service:
    type: NodePort
  extraArgs:
  - --insecure

  config: 
    kustomize.buildOptions: '--enable-helm'
