apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: flask
Name: flask
repo: https://lucasrod16.github.io/helm-charts/
chartVersion: 0.1.3

releaseName: flask
releaseNamespace: flask
values: values.yaml
